/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package folhadepagamento;

import enums.UserRole;
import models.Empregado.Horista;
import models.Endereco;
import models.Usuario;
import db.DB;
import javax.swing.JOptionPane;
import models.Empregado.Assalariado;
import models.Empregado.Comissionado;
import models.Empregado.Empregado;
/**
 *
 * @author lucas
 */
public class CadastraEmpregado extends javax.swing.JFrame {

    /**
     * Creates new form CadastraEmpregado
     */
    public CadastraEmpregado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNome = new javax.swing.JTextField();
        txtLogradouro = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        txtComplemento = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        comboUFs = new javax.swing.JComboBox<>();
        txtCEP = new javax.swing.JTextField();
        comboTipo = new javax.swing.JComboBox<>();
        checkSindicato = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        txtUsu = new javax.swing.JTextField();
        txtPass = new javax.swing.JTextField();
        txtMoney = new javax.swing.JTextField();
        txtComission = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNome.setText("jTextField1");
        getContentPane().add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        txtLogradouro.setText("jTextField2");
        getContentPane().add(txtLogradouro, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        txtNumero.setText("jTextField3");
        getContentPane().add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        txtComplemento.setText("jTextField4");
        getContentPane().add(txtComplemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));

        txtCidade.setText("jTextField5");
        getContentPane().add(txtCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, -1));

        comboUFs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AL", "MG", "SC", "SP", "RS" }));
        getContentPane().add(comboUFs, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, -1));

        txtCEP.setText("jTextField6");
        getContentPane().add(txtCEP, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, -1, -1));

        comboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Horista", "Assalariado", "Comissionado", " " }));
        getContentPane().add(comboTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, -1));

        checkSindicato.setText("Sindicato?");
        getContentPane().add(checkSindicato, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, -1, -1));

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, -1, -1));

        txtUsu.setText("jTextField7");
        getContentPane().add(txtUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, -1, 20));

        txtPass.setText("jTextField8");
        getContentPane().add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, -1, -1));

        txtMoney.setText("jTextField1");
        getContentPane().add(txtMoney, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, -1, -1));

        txtComission.setText("jTextField1");
        getContentPane().add(txtComission, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, -1, -1));

        setSize(new java.awt.Dimension(416, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Empregado emp = null;
        int selected = comboTipo.getSelectedIndex();
        Endereco end = new Endereco();
        end.setLogradouro(txtLogradouro.getText());
        end.setNumero(txtNumero.getText());
        end.setCidade(txtCidade.getText());
        end.setUf(comboUFs.getSelectedItem().toString());
        end.setCep("57035180");
        end.setComplemento(txtComplemento.getText());
        Usuario usuario = new Usuario(txtUsu.getText(), txtPass.getText(), UserRole.EMPLOYEE);
        switch (selected) {
            case 0:
                Horista horista = new Horista();
                horista.setName(txtNome.getText());
                horista.setEndereco(end);
                horista.setSalarioPorHora(Double.parseDouble(txtMoney.getText()));
                horista.setAccess_user(usuario);
                emp = horista;
                break;
            case 1:
                Assalariado assalariado = new Assalariado();
                assalariado.setName(txtNome.getText());
                assalariado.setEndereco(end);
                assalariado.setAccess_user(usuario);
                assalariado.setSalarioMensal(Double.parseDouble(txtMoney.getText()));
                emp = assalariado;
                break;
            default:
                Comissionado com = new Comissionado();
                com.setName(txtNome.getText());
                com.setEndereco(end);
                com.setAccess_user(usuario);
                com.setSalarioMensal(Double.parseDouble(txtMoney.getText()));
                com.setTaxaComissao(Double.parseDouble(txtComission.getText()));
                emp = com;
                break;
        }
        DB.empregados.add(emp);
        JOptionPane.showMessageDialog(null, "Cadastrado com sucesso", "OK", JOptionPane.INFORMATION_MESSAGE);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastraEmpregado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastraEmpregado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastraEmpregado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastraEmpregado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastraEmpregado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkSindicato;
    private javax.swing.JComboBox<String> comboTipo;
    private javax.swing.JComboBox<String> comboUFs;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField txtCEP;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtComission;
    private javax.swing.JTextField txtComplemento;
    private javax.swing.JTextField txtLogradouro;
    private javax.swing.JTextField txtMoney;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtPass;
    private javax.swing.JTextField txtUsu;
    // End of variables declaration//GEN-END:variables
}
